# This is a basic workflow to help you get started with Actions

name: Rails tests CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      # Push events on main branch
      - master
      # Push events to branches matching feature/
      - 'feature/**'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
      - name: Install sqlite3
        run: sudo apt-get install libsqlite3-dev
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile
      - name: Create database
        run: |
          bin/rails db:setup
      - name: Run tests
        env:
          OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}
        run: | 
          bundle binstubs rspec-core
          bin/rspec
      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage-report
          path: coverage 
      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
